// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"
	"time"

	uuid "uuid"
)

const createClient = `-- name: CreateClient :exec
WITH new_address AS (
    INSERT INTO addresses (id, country, city, street)
    VALUES ($7, $8, $9, $10)
    RETURNING id
)
INSERT INTO clients (id, client_name, client_surname, birthday, gender, registration_date, address_id)
SELECT $1, $2, $3, $4, $5, $6, new_address.id
FROM new_address
`

type CreateClientParams struct {
	ClientID         uuid.UUID
	ClientName       string
	ClientSurname    string
	Birthday         time.Time
	Gender           string
	RegistrationDate time.Time
	AddressID        uuid.UUID
	Country          string
	City             string
	Street           string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.ClientID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.RegistrationDate,
		arg.AddressID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :one
WITH deleted_client AS (
    DELETE FROM clients
    WHERE clients.id = $1
    RETURNING address_id
)
DELETE FROM addresses AS a
WHERE a.id = (SELECT address_id FROM deleted_client)
RETURNING a.id
`

func (q *Queries) DeleteClient(ctx context.Context, clientID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteClient, clientID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findClientsByNameAndSurname = `-- name: FindClientsByNameAndSurname :many
SELECT c.id, c.client_name, c.client_surname, c.birthday, c.gender, c.registration_date, c.address_id, a.id, a.country, a.city, a.street
FROM clients c
JOIN addresses a ON a.id = c.address_id
WHERE c.client_name = $1 AND c.client_surname = $2
`

type FindClientsByNameAndSurnameParams struct {
	ClientName    string
	ClientSurname string
}

type FindClientsByNameAndSurnameRow struct {
	Client  Client
	Address Address
}

func (q *Queries) FindClientsByNameAndSurname(ctx context.Context, arg FindClientsByNameAndSurnameParams) ([]FindClientsByNameAndSurnameRow, error) {
	rows, err := q.db.Query(ctx, findClientsByNameAndSurname, arg.ClientName, arg.ClientSurname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClientsByNameAndSurnameRow
	for rows.Next() {
		var i FindClientsByNameAndSurnameRow
		if err := rows.Scan(
			&i.Client.ID,
			&i.Client.ClientName,
			&i.Client.ClientSurname,
			&i.Client.Birthday,
			&i.Client.Gender,
			&i.Client.RegistrationDate,
			&i.Client.AddressID,
			&i.Address.ID,
			&i.Address.Country,
			&i.Address.City,
			&i.Address.Street,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT c.id, c.client_name, c.client_surname, c.birthday, c.gender, c.registration_date, c.address_id, a.id, a.country, a.city, a.street
FROM clients c
JOIN addresses a ON a.id = c.address_id
ORDER BY c.registration_date, c.id
LIMIT $2::bigint OFFSET $1::bigint
`

type ListClientsParams struct {
	Offset *int64
	Limit  *int64
}

type ListClientsRow struct {
	Client  Client
	Address Address
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.Client.ID,
			&i.Client.ClientName,
			&i.Client.ClientSurname,
			&i.Client.Birthday,
			&i.Client.Gender,
			&i.Client.RegistrationDate,
			&i.Client.AddressID,
			&i.Address.ID,
			&i.Address.Country,
			&i.Address.City,
			&i.Address.Street,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientAddress = `-- name: UpdateClientAddress :one
UPDATE addresses AS a
SET country = $1, city = $2, street = $3
FROM clients c
WHERE c.id = $4 AND c.address_id = a.id
RETURNING c.id, c.client_name, c.client_surname, c.birthday, c.gender, c.registration_date, c.address_id, a.id, a.country, a.city, a.street
`

type UpdateClientAddressParams struct {
	Country  string
	City     string
	Street   string
	ClientID uuid.UUID
}

type UpdateClientAddressRow struct {
	Client  Client
	Address Address
}

func (q *Queries) UpdateClientAddress(ctx context.Context, arg UpdateClientAddressParams) (UpdateClientAddressRow, error) {
	row := q.db.QueryRow(ctx, updateClientAddress,
		arg.Country,
		arg.City,
		arg.Street,
		arg.ClientID,
	)
	var i UpdateClientAddressRow
	err := row.Scan(
		&i.Client.ID,
		&i.Client.ClientName,
		&i.Client.ClientSurname,
		&i.Client.Birthday,
		&i.Client.Gender,
		&i.Client.RegistrationDate,
		&i.Client.AddressID,
		&i.Address.ID,
		&i.Address.Country,
		&i.Address.City,
		&i.Address.Street,
	)
	return i, err
}
