// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"

	uuid "uuid"
)

const getImageIDByProductID = `-- name: GetImageIDByProductID :one
SELECT image_id
FROM products
WHERE id = $1 AND image_id IS NOT NULL
`

func (q *Queries) GetImageIDByProductID(ctx context.Context, productID uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getImageIDByProductID, productID)
	var image_id *uuid.UUID
	err := row.Scan(&image_id)
	return image_id, err
}

const getImageProductID = `-- name: GetImageProductID :one
SELECT id AS product_id
FROM products
WHERE image_id = $1
`

func (q *Queries) GetImageProductID(ctx context.Context, imageID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getImageProductID, imageID)
	var product_id uuid.UUID
	err := row.Scan(&product_id)
	return product_id, err
}

const linkImageToProduct = `-- name: LinkImageToProduct :one

UPDATE products
SET image_id = $1, last_update_date = now()
WHERE id = $2
RETURNING id
`

type LinkImageToProductParams struct {
	ImageID   *uuid.UUID
	ProductID uuid.UUID
}

// Сами фото хранятся в image-service; здесь только связь товара с фото.
func (q *Queries) LinkImageToProduct(ctx context.Context, arg LinkImageToProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, linkImageToProduct, arg.ImageID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const unlinkImage = `-- name: UnlinkImage :one
UPDATE products
SET image_id = NULL
WHERE image_id = $1
RETURNING id
`

func (q *Queries) UnlinkImage(ctx context.Context, imageID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, unlinkImage, imageID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
