// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	uuid "uuid"
)

type Address struct {
	ID      uuid.UUID
	Country string
	City    string
	Street  string
}

type Client struct {
	ID               uuid.UUID
	ClientName       string
	ClientSurname    string
	Birthday         time.Time
	Gender           string
	RegistrationDate time.Time
	AddressID        uuid.UUID
}

type Product struct {
	ID             uuid.UUID
	Name           string
	Category       string
	Price          float64
	AvailableStock int64
	LastUpdateDate time.Time
	SupplierID     uuid.UUID
	ImageID        *uuid.UUID
}

type Supplier struct {
	ID          uuid.UUID
	Name        string
	PhoneNumber string
	AddressID   uuid.UUID
}
