// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"time"

	uuid "uuid"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, name, category, price, available_stock, last_update_date, supplier_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateProductParams struct {
	ProductID      uuid.UUID
	Name           string
	Category       string
	Price          float64
	AvailableStock int64
	LastUpdateDate time.Time
	SupplierID     uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ProductID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.AvailableStock,
		arg.LastUpdateDate,
		arg.SupplierID,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProduct(ctx context.Context, productID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProduct, productID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, category, price, available_stock, last_update_date, supplier_id, image_id
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, productID uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.AvailableStock,
		&i.LastUpdateDate,
		&i.SupplierID,
		&i.ImageID,
	)
	return i, err
}

const listAvailableProducts = `-- name: ListAvailableProducts :many
SELECT id, name, category, price, available_stock, last_update_date, supplier_id, image_id
FROM products
WHERE available_stock > 0
ORDER BY name, id
LIMIT $2::bigint OFFSET $1::bigint
`

type ListAvailableProductsParams struct {
	Offset *int64
	Limit  *int64
}

func (q *Queries) ListAvailableProducts(ctx context.Context, arg ListAvailableProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAvailableProducts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.AvailableStock,
			&i.LastUpdateDate,
			&i.SupplierID,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExistsBySupplierID = `-- name: ProductExistsBySupplierID :one
SELECT EXISTS(SELECT 1 FROM products WHERE supplier_id = $1)
`

func (q *Queries) ProductExistsBySupplierID(ctx context.Context, supplierID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productExistsBySupplierID, supplierID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProductPriceAndStock = `-- name: UpdateProductPriceAndStock :one
UPDATE products
SET price = $1, available_stock = $2, last_update_date = now()
WHERE id = $3
RETURNING id, name, category, price, available_stock, last_update_date, supplier_id, image_id
`

type UpdateProductPriceAndStockParams struct {
	Price          float64
	AvailableStock int64
	ProductID      uuid.UUID
}

func (q *Queries) UpdateProductPriceAndStock(ctx context.Context, arg UpdateProductPriceAndStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductPriceAndStock, arg.Price, arg.AvailableStock, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.AvailableStock,
		&i.LastUpdateDate,
		&i.SupplierID,
		&i.ImageID,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET available_stock = $1, last_update_date = now()
WHERE id = $2
RETURNING id, name, category, price, available_stock, last_update_date, supplier_id, image_id
`

type UpdateProductStockParams struct {
	AvailableStock int64
	ProductID      uuid.UUID
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.AvailableStock, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.AvailableStock,
		&i.LastUpdateDate,
		&i.SupplierID,
		&i.ImageID,
	)
	return i, err
}
