// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package sqlc

import (
	"context"

	uuid "uuid"
)

const createSupplier = `-- name: CreateSupplier :exec
WITH new_address AS (
    INSERT INTO addresses (id, country, city, street)
    VALUES ($4, $5, $6, $7)
    RETURNING id
)
INSERT INTO suppliers (id, name, phone_number, address_id)
SELECT $1, $2, $3, new_address.id
FROM new_address
`

type CreateSupplierParams struct {
	SupplierID  uuid.UUID
	Name        string
	PhoneNumber string
	AddressID   uuid.UUID
	Country     string
	City        string
	Street      string
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) error {
	_, err := q.db.Exec(ctx, createSupplier,
		arg.SupplierID,
		arg.Name,
		arg.PhoneNumber,
		arg.AddressID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	return err
}

const deleteSupplier = `-- name: DeleteSupplier :one
WITH deleted_supplier AS (
    DELETE FROM suppliers
    WHERE suppliers.id = $1
    RETURNING address_id
)
DELETE FROM addresses AS a
WHERE a.id = (SELECT address_id FROM deleted_supplier)
RETURNING a.id
`

func (q *Queries) DeleteSupplier(ctx context.Context, supplierID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSupplier, supplierID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT s.id, s.name, s.phone_number, s.address_id, a.id, a.country, a.city, a.street
FROM suppliers s
JOIN addresses a ON a.id = s.address_id
WHERE s.id = $1
`

type GetSupplierRow struct {
	Supplier Supplier
	Address  Address
}

func (q *Queries) GetSupplier(ctx context.Context, supplierID uuid.UUID) (GetSupplierRow, error) {
	row := q.db.QueryRow(ctx, getSupplier, supplierID)
	var i GetSupplierRow
	err := row.Scan(
		&i.Supplier.ID,
		&i.Supplier.Name,
		&i.Supplier.PhoneNumber,
		&i.Supplier.AddressID,
		&i.Address.ID,
		&i.Address.Country,
		&i.Address.City,
		&i.Address.Street,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT s.id, s.name, s.phone_number, s.address_id, a.id, a.country, a.city, a.street
FROM suppliers s
JOIN addresses a ON a.id = s.address_id
ORDER BY s.name, s.id
`

type ListSuppliersRow struct {
	Supplier Supplier
	Address  Address
}

func (q *Queries) ListSuppliers(ctx context.Context) ([]ListSuppliersRow, error) {
	rows, err := q.db.Query(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuppliersRow
	for rows.Next() {
		var i ListSuppliersRow
		if err := rows.Scan(
			&i.Supplier.ID,
			&i.Supplier.Name,
			&i.Supplier.PhoneNumber,
			&i.Supplier.AddressID,
			&i.Address.ID,
			&i.Address.Country,
			&i.Address.City,
			&i.Address.Street,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplierAddress = `-- name: UpdateSupplierAddress :one
UPDATE addresses AS a
SET country = $1, city = $2, street = $3
FROM suppliers s
WHERE s.id = $4 AND s.address_id = a.id
RETURNING s.id, s.name, s.phone_number, s.address_id, a.id, a.country, a.city, a.street
`

type UpdateSupplierAddressParams struct {
	Country    string
	City       string
	Street     string
	SupplierID uuid.UUID
}

type UpdateSupplierAddressRow struct {
	Supplier Supplier
	Address  Address
}

func (q *Queries) UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (UpdateSupplierAddressRow, error) {
	row := q.db.QueryRow(ctx, updateSupplierAddress,
		arg.Country,
		arg.City,
		arg.Street,
		arg.SupplierID,
	)
	var i UpdateSupplierAddressRow
	err := row.Scan(
		&i.Supplier.ID,
		&i.Supplier.Name,
		&i.Supplier.PhoneNumber,
		&i.Supplier.AddressID,
		&i.Address.ID,
		&i.Address.Country,
		&i.Address.City,
		&i.Address.Street,
	)
	return i, err
}
