// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"

	uuid "uuid"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (id, data, content_type)
VALUES ($1, $2, $3)
`

type CreateImageParams struct {
	ID          uuid.UUID
	Data        []byte
	ContentType string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage, arg.ID, arg.Data, arg.ContentType)
	return err
}

const deleteImage = `-- name: DeleteImage :one
DELETE FROM images
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteImage, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getImage = `-- name: GetImage :one
SELECT id, data, content_type
FROM images
WHERE id = $1
`

type GetImageRow struct {
	ID          uuid.UUID
	Data        []byte
	ContentType string
}

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i GetImageRow
	err := row.Scan(&i.ID, &i.Data, &i.ContentType)
	return i, err
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET data = $1, content_type = $2, updated_at = now()
WHERE id = $3
RETURNING id
`

type UpdateImageParams struct {
	Data        []byte
	ContentType string
	ID          uuid.UUID
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.Data, arg.ContentType, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
