// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	uuid "uuid"
)

type Image struct {
	ID          uuid.UUID
	Data        []byte
	ContentType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
