// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	uuid "uuid"
)

type OauthState struct {
	State        string
	Provider     string
	CodeVerifier string
	ExpiresAt    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Surname      string
	Email        string
	PhoneNumber  pgtype.Text
	PasswordHash []byte
	CreatedAt    time.Time
}

type UserIdentity struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          string
	CreatedAt      time.Time
}
