// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_states.sql

package sqlc

import (
	"context"
	"time"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states
WHERE state = $1
RETURNING state, provider, code_verifier, expires_at
`

func (q *Queries) ConsumeOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.CodeVerifier,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates, expiresAt)
	return err
}

const saveOAuthState = `-- name: SaveOAuthState :exec
INSERT INTO oauth_states (state, provider, code_verifier, expires_at)
VALUES ($1, $2, $3, $4)
`

type SaveOAuthStateParams struct {
	State        string
	Provider     string
	CodeVerifier string
	ExpiresAt    time.Time
}

func (q *Queries) SaveOAuthState(ctx context.Context, arg SaveOAuthStateParams) error {
	_, err := q.db.Exec(ctx, saveOAuthState,
		arg.State,
		arg.Provider,
		arg.CodeVerifier,
		arg.ExpiresAt,
	)
	return err
}
