// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	uuid "uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, session_id, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleRefreshTokens = `-- name: DeleteStaleRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at <= $1
   OR used_at <= $2
`

type DeleteStaleRefreshTokensParams struct {
	Now        time.Time
	UsedBefore *time.Time
}

func (q *Queries) DeleteStaleRefreshTokens(ctx context.Context, arg DeleteStaleRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleRefreshTokens, arg.Now, arg.UsedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions
SET expires_at = $2
WHERE id = $1
`

type ExtendSessionParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE refresh_tokens
SET used_at = $2
WHERE id = $1
  AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	ID     uuid.UUID
	UsedAt *time.Time
}

// Помечает токен использованным, только если он ещё не был использован:
// из двух одновременных обменов одного токена пройдёт ровно один.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshTokenByHash = `-- name: RefreshTokenByHash :one
SELECT id, session_id, token_hash, created_at, expires_at, used_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) RefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, refreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = $1
WHERE id = $2
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	RevokedAt *time.Time
	UserID    uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.RevokedAt, arg.UserID)
	return err
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :exec
UPDATE sessions
SET revoked_at = $1
WHERE user_id = $2
  AND id <> $3
  AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	RevokedAt     *time.Time
	UserID        uuid.UUID
	KeepSessionID uuid.UUID
}

func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionsExcept, arg.RevokedAt, arg.UserID, arg.KeepSessionID)
	return err
}

const sessionByID = `-- name: SessionByID :one
SELECT id, user_id, created_at, expires_at, revoked_at
FROM sessions
WHERE id = $1
`

func (q *Queries) SessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
