// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	uuid "uuid"
)

const saveIdentity = `-- name: SaveIdentity :exec
INSERT INTO user_identities (id, user_id, provider, provider_user_id, email, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveIdentityParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          string
	CreatedAt      time.Time
}

func (q *Queries) SaveIdentity(ctx context.Context, arg SaveIdentityParams) error {
	_, err := q.db.Exec(ctx, saveIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users (id, name, surname, email, phone_number, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, surname, email, phone_number, password_hash, created_at
`

type SaveUserParams struct {
	ID           uuid.UUID
	Name         string
	Surname      string
	Email        string
	PhoneNumber  pgtype.Text
	PasswordHash []byte
	CreatedAt    time.Time
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const saveUserWithIdentity = `-- name: SaveUserWithIdentity :one
WITH new_user AS (
    INSERT INTO users (id, name, surname, email, phone_number, password_hash, created_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, name, surname, email, phone_number, password_hash, created_at
), new_identity AS (
    INSERT INTO user_identities (id, user_id, provider, provider_user_id, email, created_at)
    SELECT $8, new_user.id, $9, $10, new_user.email, new_user.created_at
    FROM new_user
)
SELECT id, name, surname, email, phone_number, password_hash, created_at
FROM new_user
`

type SaveUserWithIdentityParams struct {
	ID             uuid.UUID
	Name           string
	Surname        string
	Email          string
	PhoneNumber    pgtype.Text
	PasswordHash   []byte
	CreatedAt      time.Time
	IdentityID     uuid.UUID
	Provider       string
	ProviderUserID string
}

type SaveUserWithIdentityRow struct {
	ID           uuid.UUID
	Name         string
	Surname      string
	Email        string
	PhoneNumber  pgtype.Text
	PasswordHash []byte
	CreatedAt    time.Time
}

func (q *Queries) SaveUserWithIdentity(ctx context.Context, arg SaveUserWithIdentityParams) (SaveUserWithIdentityRow, error) {
	row := q.db.QueryRow(ctx, saveUserWithIdentity,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.IdentityID,
		arg.Provider,
		arg.ProviderUserID,
	)
	var i SaveUserWithIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :execrows
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID
	PasswordHash []byte
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, name, surname, email, phone_number, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, name, surname, email, phone_number, password_hash, created_at
FROM users
WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const userByIdentity = `-- name: UserByIdentity :one
SELECT users.id, users.name, users.surname, users.email, users.phone_number, users.password_hash, users.created_at
FROM users
JOIN user_identities ON user_identities.user_id = users.id
WHERE user_identities.provider = $1
  AND user_identities.provider_user_id = $2
`

type UserByIdentityParams struct {
	Provider       string
	ProviderUserID string
}

type UserByIdentityRow struct {
	User User
}

func (q *Queries) UserByIdentity(ctx context.Context, arg UserByIdentityParams) (UserByIdentityRow, error) {
	row := q.db.QueryRow(ctx, userByIdentity, arg.Provider, arg.ProviderUserID)
	var i UserByIdentityRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Surname,
		&i.User.Email,
		&i.User.PhoneNumber,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
	)
	return i, err
}
